Merged revisions 1289-1309 via svnmerge from https://software.sandia.gov/svn/public/pyutilib/trunk
........
  r1289 | wehart | 2009-08-31 22:30:50 -0600 (Mon, 31 Aug 2009) | 3 lines
  
  Updating the MANIFEST file to eliminate warnings that arose due to
  incorrect data file directory names.
........
  r1290 | wehart | 2009-09-04 15:55:53 -0600 (Fri, 04 Sep 2009) | 2 lines
  
  Adding a splay tree implementation.
........
  r1291 | wehart | 2009-09-04 19:28:14 -0600 (Fri, 04 Sep 2009) | 3 lines
  
  Misc edit to the twzzle utility to better encapsulate the functionality
  in this module.
........
  r1292 | wehart | 2009-09-07 22:23:56 -0600 (Mon, 07 Sep 2009) | 3 lines
  
  Extending the twzzl utility, to provide more control over the
  frequency of twzzl changes.
........
  r1293 | wehart | 2009-09-11 12:19:18 -0600 (Fri, 11 Sep 2009) | 8 lines
  
  Rework of run_command to ensure that subprocesses are
  terminated in a graceful manner.  I've also added various options
  to this command to control how stuff is passed into the 
  command-line process.
  
  A lesson-learned is that the SubprocessMngr class should
  not be used directly.  Interrupts are not handled by this class.
........
  r1294 | wehart | 2009-09-11 13:23:48 -0600 (Fri, 11 Sep 2009) | 2 lines
  
  Removing debugging IO.
........
  r1295 | wehart | 2009-09-11 16:50:47 -0600 (Fri, 11 Sep 2009) | 2 lines
  
  Adding an option to 'tee' the output from a command to stdout.
........
  r1296 | wehart | 2009-09-11 21:24:48 -0600 (Fri, 11 Sep 2009) | 3 lines
  
  Initial commit of the 'tee' option, which allows output to stream to 
  stdout as well as the logfile.
........
  r1297 | wehart | 2009-09-11 23:05:14 -0600 (Fri, 11 Sep 2009) | 6 lines
  
  Changes to run_command and related signal handling to...
  
  . Cleanup signal messages
  . Ensure that threads terminate, and pause to give them
    time to flush all of their output.
........
  r1298 | wehart | 2009-09-14 09:04:11 -0600 (Mon, 14 Sep 2009) | 3 lines
  
  Update of the 'tee' utility.  This method should now correctly
  terminate gracefully ... and this may even work on MSWindows!?!
........
  r1299 | wehart | 2009-09-14 14:26:27 -0600 (Mon, 14 Sep 2009) | 2 lines
  
  Update to specify shell subcommands.
........
  r1300 | wehart | 2009-09-14 20:10:11 -0600 (Mon, 14 Sep 2009) | 3 lines
  
  Rework of this test, to explicitly indicate that these tests are
  for shell commands.
........
  r1301 | wehart | 2009-09-14 22:59:28 -0600 (Mon, 14 Sep 2009) | 10 lines
  
  Changing run_command() semantics.  By default, this assumes that a shell
  is used to execute the subprocess.
  
  Although this differs from the Python defaults in the subprocess package,
  the reality is that all of our uses of run_command in pyutilib, fast and
  coopr make this assumption!  Further, the subprocess.Popen() function doesn't
  clearly fail when passed a string that assumes a shell.  The output is often
  an empty log file. {sigh}  Thus, tracking down run_command() with the shell
  disabled (the former default) was quite difficult/time consuming.
........
  r1302 | wehart | 2009-09-15 11:32:59 -0600 (Tue, 15 Sep 2009) | 2 lines
  
  Removing misc imports
........
  r1303 | wehart | 2009-09-15 16:42:32 -0600 (Tue, 15 Sep 2009) | 5 lines
  
  Bug fixes:
  
  . Removing unused imports in processmngr.py
  . Adding WindowsError to the pyutilib namespace.
........
  r1304 | wehart | 2009-09-16 07:16:05 -0600 (Wed, 16 Sep 2009) | 3 lines
  
  Bug fix.  Only terminate when no data is returned.  _That_ is an
  indication of EOF.
........
  r1305 | jwatson | 2009-09-16 07:51:27 -0600 (Wed, 16 Sep 2009) | 3 lines
  
  Teeing in run_command if the "tee" option is either None (the default in the function call) or False. This allows callers to always specify a value for the option; without this, tee=False was not yielding tee behavior.
........
  r1306 | wehart | 2009-09-16 12:08:46 -0600 (Wed, 16 Sep 2009) | 11 lines
  
  Rework to enable termination of commands launched in a subshell.
  
  This wasn't working earlier because I wasn't calling killpg(), which is
  needed to kill the process group.
  
  Unfortunately, this code currently causes an exception as Python is closing down:
    "Exception AttributeError: "'NoneType' object has no attribute 'error'" in <bound method Popen.__del__ ..."
  
  This is due to a known bug in Python (see http://bugs.python.org/issue5099).  This is annoying, but it doesn't 
  impact the execution of this code.
........
  r1307 | wehart | 2009-09-16 12:45:29 -0600 (Wed, 16 Sep 2009) | 3 lines
  
  Adding a hack to suppress a subprocess.Popen exception, which 
  is a known error.
........
  r1308 | wehart | 2009-09-16 13:56:37 -0600 (Wed, 16 Sep 2009) | 2 lines
  
  Bug fix.
........
  r1309 | wehart | 2009-09-16 15:25:55 -0600 (Wed, 16 Sep 2009) | 2 lines
  
  Adding a filter option to PyUnit tests.
........